### ISSUE TITLE
Problem installing requirements

### ISSUE THREAD

**Issue by sasatefa2009** [anilbaranyelken/tulpar#2]
when i try 
pip install ir requirments

i get this

Collecting ir
  Could not fetch URL https://pypi.python.org/simple/ir/: There was a problem confirming the ssl certificate: [Errno 2] No such file or directory - skipping
  Could not find a version that satisfies the requirement ir (from versions: )
No matching distribution found for ir

i had to install the requirements manually

**Comment by ghost** [comment]
Hi,

I solve this problem.If it is possible, could you please try following
command:

pip install -r requirments

Best regards...

2017-09-02 11:48 GMT+03:00 sasatefa2009 <notifications@github.com>:
